# 16M param model stats here

n_embd = 256 # MuP minimum
n_layer = 16
n_head = 2

batch_size = 4
block_size = 4096 # ctx_len
eval_interval = 20
grad_accum_steps = 4 # basically microbatch

lr = 3e-3
min_lr = 3e-4

max_iters = 15000
eval_iters = 20
warmup_iters = 200 

dropout = 0.0
weight_decay = 0.01

v_res = true # value residual
HyperC = true # hyper connections

streams = 4

data_dir = "synth"

